### ISSUE TITLE
validity of plugin

### ISSUE THREAD

**Issue by suhaschitade** [romk1n/PhoneGap-Braintree-iOS#1]
Hi Roman,
Nice to see plugin for braintree. I saw it didn't updated from last 2 yrs hence not sure about its validity.

Could you please let me know if I can use it safely in my application

Regards,
Suhas

**Comment by romk1n** [comment]
@suhaschitade the plugin was done as part of the hackaton and was open sourced. i believe braintree sdks has changed a lot since then and i wouldn't think it works properly.

**Comment by suhaschitade** [comment]
Thanks for quick response Roman. I'll check out for other plugins although I believe there is no need of plugin really

Regards,
Suhas

Sent from my Windows Phone
